[phases.setup]
nixPkgs = ['nodejs', 'python39', 'python39Packages.pip', 'python39Packages.setuptools', 'python39Packages.wheel']
aptPkgs = ['python3-pip']

[phases.install]
cmds = [
  'python3 -m ensurepip',
  'python3 -m pip install --no-cache-dir -r requirements.txt',
  'npm install'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'gunicorn wsgi:app --bind=0.0.0.0:$PORT --log-file -'

[deploy]
startCommand = 'gunicorn wsgi:app --bind=0.0.0.0:$PORT --log-file -'
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 