[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'nodejs', 'npm']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'python -m pip install -r requirements.txt',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT run:app' 