[phases.setup]
nixPkgs = ['nodejs', 'python39', 'python39Packages.pip', 'gcc']

[phases.install]
cmds = [
  'python -m ensurepip --upgrade',
  'python -m pip install --no-cache-dir -r requirements.txt',
  'npm install'
]

[phases.build]
cmds = [
  'mkdir -p static/css',
  'npm run build'
]

[start]
cmd = 'gunicorn wsgi:app --bind=0.0.0.0:$PORT' 